wrapException: use safe-exceptions.
This was actually causing us to not wrap some exceptions at all, rather
than swallowing async ones, which is interesting.